news_keywords = {
    # Politics - Named figures & parties
    'Christopher Lawrence Bong Go': 'Politics',
    'Paolo Benigno Bam Aquino' : 'Politics',
    'Ronald Bato dela Rosa': 'Politics',
    'Erwin Tulfo': 'Politics',
    'Francis Kiko Pangilinan': 'Politics',
    'Rodante Marcoleta': 'Politics',
    'Panfilo Ping Lacson': 'Politics',
    'Vicente Tito Sotto': 'Politics',
    'Pilar Juliana Pia Cayetano': 'Politics',
    'Camille Villar': 'Politics',
    'Manuel Lito Lapid': 'Politics',
    'Maria Imelda Imee Marcos': 'Politics',
    'PDP-Laban': 'Politics',
    'Katipunan ng Nagkakaisang Pilipino': 'Politics',
    'Lakas-CMD': 'Politics',
    'Liberal Party': 'Politics',
    'Independent': 'Politics',
    "Nationalist People's Coalition": 'Politics',
    'Nacionalista Party': 'Politics',
    'Akbayan': 'Politics',
    '4Ps': 'Politics',
    'Philreca': 'Politics',
    'BBM': 'Politics',
    'Marcos': 'Politics',
    'Sara Duterte': 'Politics',
    'Inday Sara': 'Politics',

    # Health 
    'outbreak': 'Health',
    'pandemic': 'Health',
    'epidemic': 'Health',
    'COVID-19': 'Health',
    'coronavirus': 'Health',
    'SARS-CoV-2': 'Health',
    'flu': 'Health',
    'influenza': 'Health',
    'H1N1': 'Health',
    'H5N1': 'Health',
    'vaccine': 'Health',
    'vaccination': 'Health',
    'quarantine': 'Health',
    'lockdown': 'Health',
    'isolation': 'Health',
    'mask mandate': 'Health',
    'social distancing': 'Health',
    'contact tracing': 'Health',
    'testing centers': 'Health',
    'rapid test': 'Health',
    'PCR test': 'Health',
    'hospital': 'Health',
    'ICU': 'Health',
    'ventilator': 'Health',
    'health worker': 'Health',
    'healthcare system': 'Health',
    'mental health': 'Health',
    'depression': 'Health',
    'anxiety': 'Health',
    'suicide': 'Health',
    'dengue': 'Health',
    'measles': 'Health',
    'cholera': 'Health',
    'ebola': 'Health',
    'Zika virus': 'Health',
    'malaria': 'Health',
    'health advisory': 'Health',
    'public health': 'Health',
    'Philippine Health Insurance Corporation': 'Health',
    'PhilHealth': 'Health',
    'hospital bills': 'Health',
    'health protocols': 'Health',
    'Mpox': 'Health',

        # Nature & Environment
    'eco': 'Nature',
    'ecosystem': 'Nature',
    'biodiversity': 'Nature',
    'conservation': 'Nature',
    'wildlife': 'Nature',
    'deforestation': 'Nature',
    'reforestation': 'Nature',
    'forest': 'Nature',
    'natural resources': 'Nature',
    'pollution': 'Nature',
    'air pollution': 'Nature',
    'water pollution': 'Nature',
    'plastic pollution': 'Nature',
    'marine life': 'Nature',
    'ocean': 'Nature',
    'coral reef': 'Nature',
    'endangered species': 'Nature',
    'habitat loss': 'Nature',
    'climate change': 'Nature',
    'global warming': 'Nature',
    'carbon footprint': 'Nature',
    'sustainability': 'Nature',
    'renewable energy': 'Nature',
    'solar power': 'Nature',
    'wind power': 'Nature',
    'greenhouse gases': 'Nature',
    'wildfires': 'Nature',
    'earth day': 'Nature',
    'environmental policy': 'Nature',
    'environmental protection': 'Nature',
    'organic farming': 'Nature',
    'soil erosion': 'Nature',
    'water conservation': 'Nature',
    'nature reserve': 'Nature',
    'park': 'Nature',
    'flora': 'Nature',
    'fauna': 'Nature',
    'natural disaster': 'Nature',
    'environmental impact': 'Nature',

    # Politics & Governance (General)
    'Senate': 'Politics',
    'Congress': 'Politics',
    'House of Representatives': 'Politics',
    'COMELEC': 'Politics',
    'cha-cha': 'Politics',
    'red-tagging': 'Politics',
    'EDSA': 'Politics',
    'Martial Law': 'Politics',
    'SONA': 'Politics',
    'barangay elections': 'Politics',
    'SK elections': 'Politics',

     # Law & Justice
    'DOJ': 'Law',
    'Department of Justice': 'Law',
    'NBI': 'Law',
    'PNP': 'Law',
    'CIDG': 'Crime',  # Overridden to Crime
    'ICC': 'Law',
    'EJK': 'Law',
    'plunder': 'Law',
    'graft': 'Law',
    'corruption': 'Law',
    'warrant of arrest': 'Law',
    'Bilibid': 'Law',
    'illegal drugs': 'Law',
    'shabu': 'Law',
    'bail': 'Law',
    'case filed': 'Law',
    'dismissed': 'Law',

    # Economy & Business
    'inflation': 'Economy',
    'GDP': 'Economy',
    'peso-dollar exchange': 'Economy',
    'forex': 'Economy',
    'NEDA': 'Economy',
    'BIR': 'Economy',
    'BOC': 'Economy',
    'SM': 'Economy',
    'Ayala': 'Economy',
    'Jollibee': 'Economy',
    'fuel prices': 'Economy',
    'oil hike': 'Economy',
    'rollback': 'Economy',
    'job fair': 'Economy',
    'unemployment': 'Economy',
    'remittances': 'Economy',
    'OFW': 'Economy',
    'SSS': 'Economy',
    'Pag-IBIG': 'Economy',
    'PhilHealth': 'Economy',
    'interest rate': 'Economy',
    'minimum wage': 'Economy',
    'labor force': 'Economy',
    'cost of living': 'Economy',
    'train law': 'Economy',
    'economic growth': 'Economy',
    'debt-to-GDP ratio': 'Economy',
    'foreign direct investment': 'Economy',
    'stock market': 'Economy',
    'Philippine Stock Exchange': 'Economy',

    # Crime (General)
    'crime rate': 'Crime',
    'police report': 'Crime',
    'arrested': 'Crime',
    'crime scene': 'Crime',
    'victim': 'Crime',
    'suspect': 'Crime',
    'witness': 'Crime',
    'detained': 'Crime',
    'investigation': 'Crime',

    # Murder
    'murder': 'Crime',
    'homicide': 'Crime',
    'shooting': 'Crime',
    'gunman': 'Crime',
    'assassination': 'Crime',
    'extrajudicial killing': 'Crime',

    # Theft
    'robbery': 'Crime',
    'theft': 'Crime',
    'snatching': 'Crime',
    'hold-up': 'Crime',
    'burglary': 'Crime',
    'ATM skimming': 'Crime',

    # Cybercrime
    'identity theft': 'Crime',
    'phishing': 'Crime',
    'cybercrime': 'Crime',
    'hacking': 'Crime',  # Also appears under Tech
    'online scam': 'Crime',
    'Crimes': 'Crime',

    # Corruption & Money Laundering
    'money laundering': 'Corruption',
    'embezzlement': 'Corruption',
    'kickback': 'Corruption',
    'bribery': 'Corruption',
    'ghost projects': 'Corruption',
    'public funds misuse': 'Corruption',
    'COA report': 'Corruption',
    'plunder case': 'Corruption',
    'Sandiganbayan': 'Corruption',

    # Accidents & Public Safety
    'car crash': 'Accident',
    'vehicular accident': 'Accident',
    'bus accident': 'Accident',
    'hit and run': 'Accident',
    'fatal accident': 'Accident',
    'ambulance': 'Accident',
    'rescue operation': 'Accident',
    'fire': 'Accident',
    'explosion': 'Accident',
    'burn victim': 'Accident',
    'plane crash': 'Accident',
    'helicopter crash': 'Accident',
    'shipwreck': 'Accident',
    'maritime accident': 'Accident',
    'train derailment': 'Accident',
    'construction accident': 'Accident',
    'building collapse': 'Accident',
    'occupational hazard': 'Accident',
    'safety violation': 'Accident',

    # Disasters & Environment
    'PHIVOLCS': 'Disaster',
    'earthquake': 'Disaster',
    'volcano': 'Disaster',
    'storm signal': 'Disaster',
    'typhoon': 'Disaster',
    'LPA': 'Disaster',
    'flooding': 'Disaster',
    'landslide': 'Disaster',
    'evacuation': 'Disaster',
    'El Niño': 'Disaster',
    'La Niña': 'Disaster',
    'climate change': 'Disaster',
    'global warming': 'Disaster',
    'DENR': 'Disaster',

    # Public Safety & Transport
    'MMDA': 'Transport',
    'traffic': 'Transport',
    'coding': 'Transport',
    'LTO': 'Transport',
    'LTFRB': 'Transport',
    'road accident': 'Transport',
    'collision': 'Transport',
    'No Contact Apprehension': 'Transport',
    'NAIA': 'Transport',
    'flight delayed': 'Transport',
    'airport chaos': 'Transport',
    'UV Express': 'Transport',
    'jeepney phaseout': 'Transport',
    'PUV strike': 'Transport',

    # Education
    'DepEd': 'Education',
    'CHED': 'Education',
    'K-12': 'Education',
    'modular learning': 'Education',
    'class suspension': 'Education',
    'academic freeze': 'Education',
    'scholarship': 'Education',
    'board exams': 'Education',
    'campus journalism': 'Education',

    # Health
    'DOH': 'Health',
    'COVID-19': 'Health',
    'vaccine': 'Health',
    'quarantine': 'Health',
    'Dengue': 'Health',
    'measles': 'Health',
    'hospital bills': 'Health',
    'mental health': 'Health',
    'depression': 'Health',
    'suicide': 'Health',

    # Agriculture & Food
    'DA': 'Agriculture',
    'NFA': 'Agriculture',
    'rice importation': 'Agriculture',
    'onion prices': 'Agriculture',
    'smuggling': 'Agriculture',
    'price ceiling': 'Agriculture',
    'food shortage': 'Agriculture',
    'supply chain': 'Agriculture',

    # Media & Technology
    'SIM card registration': 'Tech',
    'cyber libel': 'Tech',
    'fake news': 'Tech',
    'NTC': 'Tech',
    'shutdown': 'Tech',
    'ABS-CBN': 'Tech',
    'data breach': 'Tech',
    'hacking': 'Tech',
    'TikTok': 'Tech',
    'AI': 'Tech',
    'chatbot': 'Tech',

    # Entertainment
    'celebrity wedding': 'Entertainment',
    'hiwalayan': 'Entertainment',
    'scandal': 'Entertainment',
    'viral video': 'Entertainment',
    'vlogger': 'Entertainment',
    'TV ratings': 'Entertainment',
    'blockbuster': 'Entertainment',
    'MMFF': 'Entertainment',
    'showbiz exclusives': 'Entertainment',
    'comeback': 'Entertainment',
}
